### ISSUE TITLE
on hide / show not re-rendering

### ISSUE THREAD

**Issue by peteringram0** [d-oliveros/angular-sticky#23]
When using this plugin i am hiding the section that i am using 'sticky' on then showing the section on larger devices. The plugin works fine until the section is hided then shown again.

**Comment by d-oliveros** [comment]
Hmm... the problem is that the width of the element is being calculated on load, to keep the element's width even when position: fixed. I'll hapilly merge a PR if someone manages to fix this :)

In the meanwhile, you can use ng-if instead of ng-show, as @trevcor suggested.
