### ISSUE TITLE
Media query issue

### ISSUE THREAD

**Issue by RustyDev** [d-oliveros/angular-sticky#26]
Media query functionality works well on page load but not on resize. The sticky class is still applied.

**Comment by d-oliveros** [comment]
Ok, thanks for noting it up, I'll try to fix it as soon as I have some time!

**Comment by d-oliveros** [comment]
Hey @RustyDev, I just pushed a fix to this issue. Please, let me know if you still experience issues wit this new version :)

**Comment by cve** [comment]
We still have this problem... Could you confirm that it should working?
