### ISSUE TITLE
Body class not removed on destroy

### ISSUE THREAD

**Issue by Fumoffu** [d-oliveros/angular-sticky#27]
When a sticky element is destroyed, the body class is not removed.

Here an example : http://plnkr.co/edit/75O2jpZCi5ZfUcTIHosW

Is this a normal behaviour ?

**Comment by d-oliveros** [comment]
Hi Fumoffu. It is not, thanks for noting it up! I'll try to fix it as soon as I have some time.

**Comment by d-oliveros** [comment]
Hey @Fumoffu, I just fixed this bug, and released a new version. Again, thanks for noting it up! :)
