### ISSUE TITLE
Sticky class not being set

### ISSUE THREAD

**Issue by bubbleheadinc** [d-oliveros/angular-sticky#29]
Hi. Thanks for the new version. I installed via bower and get v1.7.7 and it no longer sets the sticky-class when the attribute is set, or the default.

**Comment by bubbleheadinc** [comment]
Looks like the issue is on line: 145. Shouldn't the addClass be outside the bodyClass condition?

```
if ( bodyClass ) {
  $body.addClass(bodyClass);
  $elem.addClass(stickyClass);
}
```
Works if here...
```
$elem
  .addClass(stickyClass)
  .css('width',      elem.offsetWidth+'px')
  ...
  if ( anchor === 'bottom' ) {
    $elem.css('margin-bottom', 0);
 }
```

Thanks for your time!

**Comment by LeleDev** [comment]
This should fix this https://github.com/d-oliveros/angular-sticky/pulls

**Comment by d-oliveros** [comment]
Oh wow, I think I messed that up on yesterday's commit. Thanks for noting it up! I merged your PR @LeleDev.
